spring.application.name=timely-server
app.version=@project.version@
spring.config.import=file:.env[.properties]
spring.profiles.default=dev

# Jwt
timely.jwt.secret=${JWT_SECRET:default_secret_default_secret_default_secret}
timely.jwt.expiration-millis=${JWT_EXPIRATION_MS:3600000}

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.open-in-view=false

# Executor
spring.threads.virtual.enabled=true
spring.task.execution.thread-name-prefix=vbase-

# Actuator
management.endpoints.web.exposure.include=*

# Swagger
springdoc.api-docs.path=/swagger/v3/api-docs
springdoc.swagger-ui.path=/swagger/swagger-ui.html
springdoc.show-actuator=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
