spring.application.name=timely-server
app.version=@project.version@
spring.config.import=file:.env[.properties]
spring.profiles.default=dev

# Jwt
timely.jwt.secret=${JWT_SECRET:default_secret_default_secret_default_secret}
timely.jwt.expiration-millis=${JWT_EXPIRATION_MS:3600000}

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Hikari CP
spring.datasource.hikari.minimumIdle=3
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.connectionTimeout=10000
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.leakDetectionThreshold=15000

# JPA
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.jpa.hibernate.ddl-auto=validate

# Executor
spring.threads.virtual.enabled=true
spring.task.execution.thread-name-prefix=vbase-

# Actuator
management.endpoints.web.exposure.include=*

# Swagger
springdoc.api-docs.path=/swagger/v3/api-docs
springdoc.swagger-ui.path=/swagger/swagger-ui.html
springdoc.show-actuator=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
